name: Weekly Scheduled Tasks

on:
  schedule:
    - cron: "0 2 * * 0" # Every Sunday at 2 AM UTC
  workflow_dispatch: # Manual run option

jobs:
  run-weekly-scripts:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/scraper/requirements.txt
          python -m playwright install

      - name: Run Web Scraper
        run: python backend/scraper/scraper.py

      - name: Run DB Cleaner
        run: python backend/scraper/removeOlder.py

